name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Check vendored dependencies
        run: |
          go mod tidy
          go mod verify
          go mod vendor -v
          git status
          if [[ -n "$(git status --porcelain vendor)" ]]; then
            echo 'vendor/ is out-of-date: run `go mod tidy && go mod vendor` and then check in the changes'
            echo 'If `go mod tidy && go mod vendor` results in no changes, make sure you are using the latest relase of Go'
            git status --porcelain vendor
            exit 1
          fi
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
  build:
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Build CI tool
        working-directory: tools/ci
        run: go build
      - name: Build
        run: ./tools/ci/ci -verbose -build
          -go=${{ matrix.go-version }}
          -buildtoolchain="std,tamago,tinygo"
          -arch="amd64,arm,arm64,riscv64"
          -platform=linux
  test:
    needs:
      - build
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Build CI tool
        working-directory: tools/ci
        run: go build
      - name: Run tests
        run: ./tools/ci/ci -verbose -test
          -go=${{ matrix.go-version }}
          -env="UROOT_SOURCE=${{ github.workspace }}"
  race:
    needs:
      - test
    strategy:
      matrix:
        go-version: [ '1.18', '1.19', '1.20' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Build CI tool
        working-directory: tools/ci
        run: go build
      - name: Run tests
        run: ./tools/ci/ci -verbose -test
          -go=${{ matrix.go-version }}
          -env="UROOT_SOURCE=${{ github.workspace }},GOMAXPROCS=1"
          -race
